version: "3.8"

services:
  # postgres:
  #   container_name: db_postgres
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: task-demo
  #   ports:
  #     - 5432:5432
  #   expose:
  #     - 5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: frontend-dev
    build:
      context: .
      target: dev
    restart: always
    command: npm run docker:dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    env_file: .env
    # depends_on:
    #   - postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  pgdata: {}
